##########
# GITHUB #
##########

# Current workflow
# @see https://github.com/cylmat/phpconfig/actions

# Doc
# @see https://github.com/actions/starter-workflows

name: PHP Composer

on:
  push:
    branches: [ main, action ]

jobs:
  build:

    runs-on: ubuntu-latest
    name: Build and test
    strategy:
      fail-fast: false
      matrix:
          php: [7.4, 8.0, 8.1, 8.2]

    steps:
    - uses: actions/checkout@v3
      with: 
        ref: main

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        coverage: xdebug
        extensions: intl, mbstring
        php-version: "${{ matrix.php }}"

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Download bins and composer dependencies
      run: |
        sed -i -e 's/make/sudo make/' Makefile
        sudo make install-all

    - name: Run all linters and tests
      run: make all
